#%RAML 1.0 DataType
displayName: Carrier Prod Line
description: Defines the fields in Carrier Prod Line type

type: object
properties:
  status?: 
    type: integer
    default: 0
  recordstobeprocessed?: 
    type: integer
    default: 0