#%RAML 1.0 DataType
displayName: Extract status
description: Defines the fields in Extract status type

type: object
properties:
  carrier:
    type: !include carrier.raml
  carrierprodline:
    type: !include carrierProdline.raml
  carrierprodcompline:
    type: !include carrierProdCompline.raml